web:
  context: /backstage

tasks:
  Backgroundable:
    concurrency: 0

environment:
# Add users to $JBOSS_HOME/server/default/conf/props/torquebox-users.properties
# or just call rake torquebox:auth:adduser CREDENTIALS=user:pass from the command line
#  REQUIRE_AUTHENTICATION: true
