web:
  context: /backstage

tasks:
  Backgroundable:
    concurrency: 0

environment:
# set a username and password here to require authentication to Backstage
#  USERNAME: backstage
#  PASSWORD: pass
