web:
  context: /backstage
  static: public

tasks:
  Backgroundable:
    concurrency: 0

ruby:
  version: 1.9

environment:
# Add users to $JBOSS_HOME/server/default/conf/props/torquebox-users.properties
# or just call rake torquebox:auth:adduser CREDENTIALS=user:pass from the command line
#  REQUIRE_AUTHENTICATION: true
